---
- hosts: local
  become: yes
  connection: local
  
  tasks:
  - name: ansible_builtin_command
    ansible.builtin.command: netstat -lntp  # don't support | and >. only outer env
    register: builtin_command_output

  - name: printing  command output
    ansible.builtin.debug:
      msg: printing output '{{ builtin_command_output }}'


  - name: ansible_builtin_shell
    ansible.builtin.shell: /etc/passwd | grep root #to check internal env
    register: builtin_shell_output

  - name: printing shell output
    ansible.builtin.debug:
      msg: printing output '{{ builtin_shell_output }}'
    

        