---
- hosts: slave2
  become: yes

  vars_files:
    - vars.yml
  
  tasks:
  - name: installing {{ package_installing }}
    ansible.builtin.package:
      name: "{{ package_installing }}"
      state: present
    
  - name: staring and enabling {{ service }}
    ansible.builtin.service:
      name: "{{ service }}"
      state: started  # Ensures the service is running
      enabled: true   # Ensures the service starts on boot

        