---
- hosts: local
  become: yes
  connection: local
  
  tasks:
  - name: example for loops
    ansible.builtin.package:
      name: "{{ item }}"  # item is default value for loops
      state: present
    loop:
      - nginx
      - httpd